apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170168056
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/oosstwye-tenant/test-app-170168056/java-quarkus-170168056@sha256:353e8a816b2aa103d7c72b7ad34b8f3e46202904830e02b190cbceeaee4fb97e
        name: my-java-quarkus
        resources: {}
status: {}
